name: Rest in peace, Ian <3

on:
  push:
    branches:
      - 'debian'

jobs:
  debian:
    # Verify that Debian packages can be built
    name: Debian Package
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          apt-get update
          apt-get install -y build-essential autoconf automake pkg-config \
                             libconfuse-dev libgnutls28-dev systemd       \
                             dpkg-dev debhelper devscripts
      - name: Building Debian package
        run: |
          ./autogen.sh
          ./configure
          make distcheck
          make package
          cat ../inadyn*.changes
